### ISSUE TITLE
ONA with Google Spreadsheet

### ISSUE THREAD

**Issue by higor-gomes93** [keithmcnulty/ona_book#1]
Hello, Keith!

First of all, congratulations on your new book. You are one of my main inspirations when it comes to People Analytics.

I have this little [project ](https://github.com/higor-gomes93/network-google-spreadsheet) where I created a network graph inside the Google Sheets UI. It could be a great solution for quick validations of data sets or first insights about some analysis regarding networks.

I am not sure if this is something that relates to your book, but I thought that would be nice to share with you, specially because graphs are not that easy to find in free online tools (at least, here in Brazil), in other words, this helps who has neither programming skills nor access to softwares such as Power BI. You can input your dataset, and than share it online and for free with another person.

Thank you!

**Comment by keithmcnulty** [comment]
Thanks Higor.  No-code tools are not in scope for this book, but it sounds like a useful tool you've developed.
