### ISSUE TITLE
Paths and importance

### ISSUE THREAD

**Issue by bvoorhees** [keithmcnulty/ona_book#2]
Hi Keith,

Wondering if there is room in section 7.1.3 or somewhere in chapter 6 that covers gould-fernandez brokerage measures. 

In a people analytics context I find them to be a useful step beyond betweenness centrality, as it combines the use cases of betweenness centrality but across boundaries (of course, except for the "coordinator role"). They can be the go-to people in organizational networks for bridging silos, as they already have connections across boundaries and many paths flow through them. 

Happy to contribute thinking here and provide example code from the `sna` package for this.

**Comment by keithmcnulty** [comment]
Thanks Bennett!!  I responded on the other issue you submitted and will close this one.
