### ISSUE TITLE
6.1.4 Block Density

### ISSUE THREAD

**Issue by bvoorhees** [keithmcnulty/ona_book#3]
Hi Keith,

Wondering if there is room to go further in an organizational context for density to look at within-boundary and cross-boundary density metrics (aka Block Density). I find this to be quite useful for diagnosing inadequate levels of collaboration relative to expected values (both from a mathematical definition perspective, but also from an organizational goal setting perspective). 

Happy to provide example R code for this.

**Comment by keithmcnulty** [comment]
Hi Bennett

Thanks so much for looking over the work so far.  There's always room to go further.  I have to think about the right context in the book to introduce these more advanced/specialised measures.  I think they push a bit too far for the early chapters which are focused on educating people on the basics, and certainly they are hard to introduce before Chapter 8 where the concepts of subgroup membership through cliques and communities are introduced.

The other thing I have to consider for the print version is length - my publisher is keen for the print book to not exceed 300 pages.  

I'm thinking about adding another extension chapter to cover 'additional resources', which might end up in the online only version depending on length, and will probably be entirely R focused.  I had planned to put `tidygraph` in there, and that might be a good place to put in some references to the `sna` package, including examples of these types of inter- and intra-group centrality and density measures.     So if you do want to put together some examples, I am sure I could make use of them in the book.  They key is to find data sets that make them practically useful and relevant, or else people will regard them as too abstract to be useful.  

The good news with the online book is that content can be progressively added and there is no hard deadline, so if you can find time to pull together some examples over the next few weeks I would be keen to see them and to think about how to integrate them.  One idea would be to write an R Markdown that goes through the different functions of the `sna` package that you have found useful, with some data example of each at work.  

I'll keep this issue open to follow this through, and will close the other one.

Thanks so much for your help!!
