### ISSUE TITLE
3.1.2 Bipartite graphs

### ISSUE THREAD

**Issue by Ochibobo** [keithmcnulty/ona_book#7]
Hello Keith,

Great book you have here. Thanks for sharing your knowledge. 

The definition offered on `bipartite graphs` appears to fit more into the description of `connected components`. `Bipartite graphs` are graphs whose vertices can be divided into 2 _disjoint_ and _independent_ sets __U__ and __V__ such that every edge connects a vertex in __U__ to one in __V__ ([Wikipedia](https://en.wikipedia.org/wiki/Bipartite_graph)). 
The definition provided in the book: _Bipartite graphs are graphs that have two disjoint sets of vertices, such that no vertex from one set is connected to any of the vertices in the other set_ - seems to be contradictory with what a `bipartite graph` is. For instance, if I have 2 independent vertices, say __A__ and __B__, and they have no edge between them, by the book's definition, this may qualify as a `bipartite graph`. 
Would you mind shading more light into it?

Thanks.

**Comment by keithmcnulty** [comment]
Yes you are 100% right and this is one of the corrections I need to make throughout the book, where I have used the terms bipartite and k-partite erroneously.  It is on my list to address in the next two weeks before I submit the print copy.   Many thanks for the reminder.
