### ISSUE TITLE
`onadata` Is Not Available

### ISSUE THREAD

**Issue by aliaamiri** [keithmcnulty/ona_book#8]
First and foremost, thank you for this well_researched book. The historical stuff is so interesting and softening complement to the technical part.
I cannot install `onadata` on my RStudio 4.1.2. If it is possible , similar to your last book's data package `peopleanalyticsdata`, put this one here so it can be downloaded from github directly.

The warning I encounter:
Installing package into ‘C:/Users/Ali/Documents/R/win-library/4.1’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘onadata’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages

**Comment by keithmcnulty** [comment]
I have not built the package yet.   It should be available early next year in time for the print book release.  In the meantime just follow the direct downloads for the data sets in the code.

**Comment by aliaamiri** [comment]
Thank you!
